# Step 2: Set Up Django Backend
FROM python:3.12-slim

# set workdir to /workspaces/<project_folder_name>
ENV WORKDIR /workspaces/memory

ENV DB_PATH=/workspaces/memory/flashcards.db

# Set working directory
WORKDIR ${WORKDIR}

# Install CMake and other necessary build tools
RUN apt-get update && apt-get install -y \
    cmake \
    build-essential \
    pipx \ 
    git \
    curl \
    graphviz \ 
    sqlite3 \ 
    wget

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get update && apt-get install -y nodejs

# spark install
RUN mkdir -p /etc/apt/keyrings
RUN wget -O - https://packages.adoptium.net/artifactory/api/gpg/key/public | tee /etc/apt/keyrings/adoptium.asc
RUN echo "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb $(awk -F= '/^VERSION_CODENAME/{print$2}' /etc/os-release) main" | tee /etc/apt/sources.list.d/adoptium.list
RUN apt-get update && apt-get install -y temurin-17-jdk
ENV JAVA_HOME /usr/lib/jvm/temurin-17-jdk-arm64


COPY pyproject.toml poetry.lock ${WORKDIR}

RUN pip install poetry

# RUN apt-get install -y nginx systemctl nano

EXPOSE 8000
# EXPOSE 80



