"""add tag db

Revision ID: 91cb63f6a7ff
Revises: 0cbfe9d00d77
Create Date: 2024-12-07 05:49:49.238291

"""

import sqlalchemy as sa
from alembic import op
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "91cb63f6a7ff"
down_revision: Union[str, None] = "0cbfe9d00d77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("toronto_weather")
    op.drop_table("historical_temperatures")
    op.drop_table("employees")
    op.drop_table("test_table")
    op.drop_table("user_account")
    op.drop_table("Suppliers")
    op.drop_table("customer_shopping_data_no_header")
    op.drop_table("covid_19_deaths")
    op.drop_table("pytest_expected_output")
    op.drop_table("us_videos")
    op.drop_table("academic_detail")
    op.drop_table("categories")
    op.drop_table("Categories")
    op.drop_table("Nums")
    op.drop_table("Employees")
    op.drop_table("contoso_sales")
    op.drop_table("student_performance")
    op.drop_table("status")
    op.drop_table("nums")
    op.drop_table("Shippers")
    op.drop_table("orderdetails")
    op.drop_table("testing_upload")
    op.drop_table("datasets")
    op.drop_table("scores")
    op.drop_table("titanic_dataset")
    op.drop_table("pokemon")
    op.drop_table("address")
    op.drop_table("customer_shopping_data")
    op.drop_table("your_table_name")
    op.drop_table("Customers")
    op.drop_table("tests")
    op.drop_table("OrderDetails")
    op.drop_table("Products")
    op.drop_table("orders")
    op.drop_table("google_store_reviews")
    op.drop_table("academic")
    op.drop_table("temperatures")
    op.drop_table("products")
    op.drop_table("customers")
    op.drop_table("suppliers")
    op.drop_table("Tests")
    op.drop_table("Scores")
    op.drop_table("shippers")
    op.drop_table("Orders")
    op.alter_column("code", "type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("code", "default_code", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column(
        "suspended", "date_created", existing_type=sa.DATE(), type_=sa.DateTime(timezone=True), existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "suspended", "date_created", existing_type=sa.DateTime(timezone=True), type_=sa.DATE(), existing_nullable=False
    )
    op.alter_column("code", "default_code", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("code", "type", existing_type=sa.VARCHAR(), nullable=True)
    op.create_table(
        "Orders",
        sa.Column("orderid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("custid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("empid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("orderdate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("requireddate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shippeddate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shipperid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("freight", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("shipname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shipaddress", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shipcity", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shipregion", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shippostalcode", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("shipcountry", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "shippers",
        sa.Column("shipperid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("companyname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "Scores",
        sa.Column("testid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("studentid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("score", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table("Tests", sa.Column("testid", sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table(
        "suppliers",
        sa.Column("supplierid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("companyname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("contactname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("contacttitle", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("city", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("region", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("postalcode", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("country", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fax", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "customers",
        sa.Column("custid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("companyname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("contactname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("contacttitle", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("city", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("region", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("postalcode", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("country", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fax", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "products",
        sa.Column("productid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("productname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("supplierid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("categoryid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("unitprice", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("discontinued", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "temperatures",
        sa.Column("date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("avg_temp_celsius", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.create_table(
        "academic",
        sa.Column("A", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("B", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "google_store_reviews",
        sa.Column("reviewId", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("userName", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("userImage", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("score", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("thumbsUpCount", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("reviewCreatedVersion", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("at", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("replyContent", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("repliedAt", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("sortOrder", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("appId", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "orders",
        sa.Column("orderid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("custid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("empid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("orderdate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("requireddate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shippeddate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shipperid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("freight", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("shipname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shipaddress", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shipcity", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shipregion", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shippostalcode", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("shipcountry", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "Products",
        sa.Column("productid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("productname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("supplierid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("categoryid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("unitprice", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("discontinued", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "OrderDetails",
        sa.Column("orderid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("productid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("unitprice", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("qty", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("discount", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.create_table("tests", sa.Column("testid", sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table(
        "Customers",
        sa.Column("custid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("companyname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("contactname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("contacttitle", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("city", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("region", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("postalcode", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("country", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fax", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "your_table_name",
        sa.Column("year", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("students", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("us_students", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("undergraduate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("graduate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("non_degree", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("opt", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.create_table(
        "customer_shopping_data",
        sa.Column("invoice_no", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("customer_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("gender", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("age", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("category", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("quantity", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("price", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("payment_method", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("invoice_date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("shopping_mall", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "address",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("email_address", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], name="address_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="address_pkey"),
    )
    op.create_table(
        "pokemon",
        sa.Column("#", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Type 1", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Type 2", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Total", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("HP", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Attack", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Defense", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Sp. Atk", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Sp. Def", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Speed", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Generation", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Legendary", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "titanic_dataset",
        sa.Column("PassengerId", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Survived", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Pclass", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Sex", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Age", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("SibSp", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Parch", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Ticket", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Fare", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("Cabin", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Embarked", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "scores",
        sa.Column("testid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("studentid", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("score", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("date_created", sa.DATE(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="datasets_pkey"),
    )
    op.create_table(
        "testing_upload",
        sa.Column("id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("problem_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("preprocessing_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("default_code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("date_created", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "orderdetails",
        sa.Column("orderid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("productid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("unitprice", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("qty", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("discount", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.create_table(
        "Shippers",
        sa.Column("shipperid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("companyname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table("nums", sa.Column("n", sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_table(
        "status",
        sa.Column("year", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("female", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("male", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("single", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("married", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("full_time", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("part_time", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("visa_f", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("visa_j", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("visa_other", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.create_table(
        "student_performance",
        sa.Column("gender", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("race/ethnicity", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("parental level of education", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("lunch", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("test preparation course", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("math score", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("reading score", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("writing score", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "contoso_sales",
        sa.Column("Order Number", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Line Number", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Order Date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Delivery Date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Customer Name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Customer Gender", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Customer Country", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Customer Age", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Store Name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Product Name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Color", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Brand", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Category", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Subcategory", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Quantity", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Unit Price", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("Net Price", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("Unit Cost", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("Currency Code", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Exchange Rate", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.create_table(
        "Employees",
        sa.Column("empid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("lastname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("firstname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("titleofcourtesy", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("birthdate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("hiredate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("city", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("region", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("postalcode", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("country", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("mgrid", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.create_table("Nums", sa.Column("n", sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_table(
        "Categories",
        sa.Column("categoryid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("categoryname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "categories",
        sa.Column("categoryid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("categoryname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "academic_detail",
        sa.Column("year", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("academic_type", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("academic_level", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("students", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "us_videos",
        sa.Column("video_id", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("trending_date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("channel_title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("category_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("publish_time", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("tags", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("views", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("likes", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("dislikes", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("comment_count", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("thumbnail_link", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("comments_disabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("ratings_disabled", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("video_error_or_removed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "pytest_expected_output",
        sa.Column("Name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Type 1", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Type 2", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Total", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Attack", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Defense", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Speed", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Atk Rank", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Def Rank", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Spe Rank", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "covid_19_deaths",
        sa.Column("Data As Of", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Start Date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("End Date", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Group", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Year", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("Month", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("State", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Sex", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Age Group", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("COVID-19 Deaths", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("Total Deaths", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("Pneumonia Deaths", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column(
            "Pneumonia and COVID-19 Deaths", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
        sa.Column("Influenza Deaths", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column(
            "Pneumonia, Influenza, or COVID-19 Deaths",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("Footnote", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "customer_shopping_data_no_header",
        sa.Column("I138884", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("C241288", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Female", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("28", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("Clothing", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("5", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("1500.4", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("Credit Card", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("5/8/2022", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("Kanyon", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "Suppliers",
        sa.Column("supplierid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("companyname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("contactname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("contacttitle", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("city", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("region", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("postalcode", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("country", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("fax", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "user_account",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("fullname", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="user_account_pkey"),
    )
    op.create_table(
        "test_table",
        sa.Column("A", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("B", sa.BIGINT(), autoincrement=False, nullable=True),
    )
    op.create_table(
        "employees",
        sa.Column("empid", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("lastname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("firstname", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("titleofcourtesy", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("birthdate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("hiredate", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("city", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("region", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("postalcode", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("country", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("mgrid", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.create_table(
        "historical_temperatures",
        sa.Column("datetime", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("city", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("temperature", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.create_table(
        "toronto_weather",
        sa.Column("datetime", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("temperature", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("wind_speed", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("pressure", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("humidity", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
